[package]
authors = ["Jeff Muizelaar <jrmuizel@gmail.com>"]
edition = "2018"
name = "raqote"
version = "0.2.1"
description = "2D graphics library"
license = "BSD-3-Clause"
repository = "https://github.com/jrmuizel/raqote"

[dependencies]
euclid = "0.19.8"
font-kit = "0.1.0"
lyon_geom = "0.12.4"
png = "0.14.0"
typed-arena = "1.4.1"
sw-composite = "0.1.1"
