[package]
authors = ["Jeff Muizelaar <jrmuizel@gmail.com>"]
edition = "2018"
name = "raqote"
version = "0.1.0"

[dependencies]
euclid = "0.19.8"
font-kit = {git = "https://github.com/pcwalton/font-kit" }
lyon_geom = "0.12.4"
png = "0.14.0"
typed-arena = "1.4.1"
sw-composite = {git = "https://github.com/jrmuizel/sw-composite" }
